# Site
title:              Rayna Harris PhD
bio:                " "
description:        "Rayna Harris is a scientist, educator, and community building who blogs about these things every month or so."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.raynaharris.com" # the base hostname & protocol for your site
author:
  twitter: raynamharris

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed


# Social
analytics-id:       "default"
twitter:            "raynamharris"
instagram:          "raynamharris"
github:             "raynamharris"
linkedin:           "rayna-harris-484802ba" 

# medium feed
collections:
  - external_feed
  
# RSS or Atom feed 
plugins:
  - jekyll-feed

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  
  

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
